#!/usr/bin/env bash
#
# scripts/generate_env.sh — produce a production-ready .env on the Hub VM
# without ever putting credentials in this repo.
#
# Reads from your shell environment (or interactive prompts), writes to
# ./.env, and refuses to overwrite an existing .env unless FORCE=1.
#
# Usage:
#   bash scripts/generate_env.sh                    # interactive
#   AIVEN_PASSWORD=… OL9_PASSWORD=… API_TOKEN=…  bash scripts/generate_env.sh
#   FORCE=1 …                                       # overwrite existing .env
#
# Inputs (all read from env first, prompted if missing):
#   AIVEN_HOST=pg-37455d5-matrixhub-db.c.aivencloud.com   (default)
#   AIVEN_PORT=24870                                       (default)
#   AIVEN_USER=avnadmin                                    (default)
#   AIVEN_DB=defaultdb                                     (default)
#   AIVEN_PASSWORD=<rotated Aiven password>                (REQUIRED)
#   OL9_HOST=10.0.0.185                                    (default)
#   OL9_PORT=5432                                          (default)
#   OL9_USER=matrix                                        (default)
#   OL9_DB=matrixhub                                       (default)
#   OL9_PASSWORD=<OL9 .env.db POSTGRES_PASSWORD>           (REQUIRED for fallback)
#                                                          (skip with NO_FALLBACK=1)
#   API_TOKEN=<openssl rand -hex 32>                       (auto-generated if blank)
#   MCP_GATEWAY_TOKEN=<openssl rand -hex 32>               (auto-generated if blank)
#
# Output: ./.env (mode 0600), gitignored.

set -Eeuo pipefail

OUT="${OUT:-.env}"
FORCE="${FORCE:-0}"
NO_FALLBACK="${NO_FALLBACK:-0}"

bold(){ printf '\033[1m%s\033[0m\n' "$*"; }
ok()  { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn(){ printf '  \033[33m!\033[0m %s\n' "$*"; }
bad() { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; }
info(){ printf '    %s\n' "$*"; }
hr()  { printf '%.0s-' {1..72}; printf '\n'; }
step(){ printf '\n'; bold "▶ $*"; hr; }

urlencode() { python3 -c 'import urllib.parse,sys;print(urllib.parse.quote(sys.argv[1],safe=""))' "$1"; }

[ -f "$OUT" ] && [ "$FORCE" != "1" ] && {
  bad "$OUT already exists. Re-run with FORCE=1 to overwrite, or remove it first."
  exit 1
}

step "Inputs (your shell env wins; interactive fallback otherwise)"

prompt_var() {
  # $1 var, $2 prompt, $3 default, $4 hidden(0/1)
  local var="$1" prm="$2" def="${3:-}" hidden="${4:-0}" cur val
  cur="${!var:-}"
  if [ -n "$cur" ]; then
    [ "$hidden" = "1" ] && info "$var = (from env, hidden)" || info "$var = $cur"
    return
  fi
  if [ "$hidden" = "1" ]; then
    read -r -s -p "  $prm: " val; echo
  else
    if [ -n "$def" ]; then
      read -r -p   "  $prm [$def]: " val; val="${val:-$def}"
    else
      read -r -p   "  $prm: " val
    fi
  fi
  printf -v "$var" '%s' "$val"
  export "$var"
}

prompt_var AIVEN_HOST     "Aiven host"     "pg-37455d5-matrixhub-db.c.aivencloud.com" 0
prompt_var AIVEN_PORT     "Aiven port"     "24870"                                     0
prompt_var AIVEN_USER     "Aiven user"     "avnadmin"                                  0
prompt_var AIVEN_DB       "Aiven database" "defaultdb"                                 0
prompt_var AIVEN_PASSWORD "Aiven password (hidden)" ""                                 1
[ -n "${AIVEN_PASSWORD:-}" ] || { bad "AIVEN_PASSWORD is required"; exit 1; }

if [ "$NO_FALLBACK" != "1" ]; then
  prompt_var OL9_HOST     "OL9 private IP" "10.0.0.185" 0
  prompt_var OL9_PORT     "OL9 port"       "5432"        0
  prompt_var OL9_USER     "OL9 user"       "matrix"      0
  prompt_var OL9_DB       "OL9 database"   "matrixhub"   0
  prompt_var OL9_PASSWORD "OL9 password (hidden, skip if decommissioned)" "" 1
fi

# Auto-generate any missing tokens
gen_token() { openssl rand -hex 32; }
[ -n "${API_TOKEN:-}" ]         || { API_TOKEN="$(gen_token)";         ok "API_TOKEN auto-generated"; }
[ -n "${MCP_GATEWAY_TOKEN:-}" ] || { MCP_GATEWAY_TOKEN="$(gen_token)"; ok "MCP_GATEWAY_TOKEN auto-generated"; }

# URL-encode passwords so @, :, /, # in them don't break the URI
AIVEN_ENC="$(urlencode "$AIVEN_PASSWORD")"
PRIMARY_URL="postgresql+psycopg://${AIVEN_USER}:${AIVEN_ENC}@${AIVEN_HOST}:${AIVEN_PORT}/${AIVEN_DB}?sslmode=require"

FALLBACK_LINE=""
if [ "$NO_FALLBACK" != "1" ] && [ -n "${OL9_PASSWORD:-}" ]; then
  OL9_ENC="$(urlencode "$OL9_PASSWORD")"
  FALLBACK_LINE="DATABASE_URL_FALLBACK=postgresql+psycopg://${OL9_USER}:${OL9_ENC}@${OL9_HOST}:${OL9_PORT}/${OL9_DB}"
else
  FALLBACK_LINE="# DATABASE_URL_FALLBACK=  # OL9 decommissioned or no password supplied"
fi

step "Writing $OUT"
umask 077    # 0600 mode for the resulting file
cat > "$OUT" <<EOF
# Generated by scripts/generate_env.sh on $(date -u +%FT%TZ).
# DO NOT COMMIT — already in .gitignore.

# --- Server ---
APP_NAME=matrix-hub
HOST=0.0.0.0
PORT=443
LOG_LEVEL=INFO
PUBLIC_BASE_URL=https://api.matrixhub.io

# --- Auth ---
API_TOKEN=${API_TOKEN}
REQUIRE_API_TOKEN_IN_PROD=true

# --- Database (boot-time selector picks primary, falls back if down) ---
DATABASE_URL_PRIMARY=${PRIMARY_URL}
${FALLBACK_LINE}
# PROBE_TIMEOUT=5
# PROBE_RETRIES=2
# ON_FALLBACK=warn   # warn | require | fail

# --- CORS ---
CORS_ALLOW_ORIGINS=["https://matrixhub.io","https://www.matrixhub.io","https://matrixhub.vercel.app"]
CORS_ALLOW_CREDENTIALS=false

# --- Search ---
SEARCH_LEXICAL_BACKEND=pgtrgm
SEARCH_VECTOR_BACKEND=none
SEARCH_DEFAULT_MODE=keyword
SEARCH_INCLUDE_PENDING_DEFAULT=true
SEARCH_HYBRID_WEIGHTS=sem:0.6,lex:0.4,rec:0.1,q:0.1
RAG_ENABLED=false

# --- Catalog ingestion ---
CATALOG_REMOTES=["https://raw.githubusercontent.com/agent-matrix/catalog/main/index.json"]
INGEST_SCHED_ENABLED=true
INGEST_INTERVAL_MIN=15

# --- MCP Gateway ---
MCP_GATEWAY_URL=http://127.0.0.1:4444
MCP_GATEWAY_TOKEN=${MCP_GATEWAY_TOKEN}
EOF
chmod 0600 "$OUT"

step "Verification"
ok "wrote $OUT (mode $(stat -c '%a' "$OUT" 2>/dev/null || stat -f '%A' "$OUT"))"
masked="$(sed -E 's#(://[^:]+:)[^@]+(@)#\1***\2#g; s#(API_TOKEN=).{8,}#\1***#; s#(MCP_GATEWAY_TOKEN=).{8,}#\1***#' "$OUT")"
echo "$masked" | sed 's/^/    /'

# scrub script-local creds from this shell so they don't leak via `env` into a child process.
unset AIVEN_PASSWORD OL9_PASSWORD AIVEN_ENC OL9_ENC PRIMARY_URL FALLBACK_LINE 2>/dev/null || true

step "Next"
info "  bash scripts/test_db.sh                   # validate Aiven schema + round-trip"
info "  docker stop matrixhub && docker rm matrixhub"
info "  bash scripts/build_container.sh           # rebuild with new entrypoint + scripts/"
info "  bash scripts/run_container.sh"
info "  curl -ksS https://127.0.0.1:443/health?check_db=true"
bold "✓ generate_env.sh complete"
