"""${message}

Revision ID: ${repr(up_revision)}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) Create entity table (with its CHECK CONSTRAINT)
    op.create_table(
        'entity',
        sa.Column('uid', sa.String(), primary_key=True, nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('license', sa.String(), nullable=True),
        sa.Column('homepage', sa.String(), nullable=True),
        sa.Column('source_url', sa.String(), nullable=True),
        sa.Column('tenant_id', sa.String(), nullable=False, server_default=sa.text("'public'")),
        # JSON arrays with jsonb defaults (PostgreSQL). Works fine on PG; SQLite will ignore ::jsonb in dev if needed.
        sa.Column('capabilities', sa.JSON(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column('frameworks', sa.JSON(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column('providers', sa.JSON(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column('readme_blob_ref', sa.String(), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=False, server_default=sa.text("0.0")),
        sa.Column('release_ts', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP"),
                  onupdate=sa.text("CURRENT_TIMESTAMP")),
        # Legacy MCP gateway fields (kept for backward-compat)
        sa.Column('gateway_registered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('gateway_error', sa.Text(), nullable=True),
        sa.Column('mcp_registration', sa.JSON(), nullable=True),
        # NEW: A2A/native protocols + protocol-specific manifests
        sa.Column('protocols', sa.JSON(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column('manifests', sa.JSON(), nullable=True),
        # Inline check constraint (SQLite-friendly)
        sa.CheckConstraint(
            "type in ('agent','tool','mcp_server')",
            name="ck_entity_type"
        ),
    )
    op.create_index('ix_entity_type_name', 'entity', ['type', 'name'])
    op.create_index('ix_entity_created_at', 'entity', ['created_at'])

    # Optional Postgres-only GIN for fast protocol filtering
    op.execute("""
    CREATE INDEX IF NOT EXISTS gin_entity_protocols
      ON entity USING gin (protocols jsonb_path_ops);
    """)

    # 2) Create remote table
    op.create_table(
        'remote',
        sa.Column('url', sa.String(), primary_key=True, nullable=False),
    )

    # 3) Create embedding_chunk table
    op.create_table(
        'embedding_chunk',
        sa.Column('entity_uid', sa.String(),
                  sa.ForeignKey('entity.uid', ondelete='CASCADE'),
                  primary_key=True, nullable=False),
        sa.Column('chunk_id', sa.String(), primary_key=True, nullable=False),
        sa.Column('vector', sa.JSON(), nullable=True),
        sa.Column('caps_text', sa.String(), nullable=True),
        sa.Column('frameworks_text', sa.String(), nullable=True),
        sa.Column('providers_text', sa.String(), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=True),
        sa.Column('embed_model', sa.String(), nullable=True),
        sa.Column('raw_ref', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("CURRENT_TIMESTAMP"),
                  onupdate=sa.text("CURRENT_TIMESTAMP")),
    )
    op.create_index('ix_embedding_chunk_updated_at', 'embedding_chunk', ['updated_at'])

    # 4) NEW: generic per-target registration status table
    op.create_table(
        'entity_registration',
        sa.Column('entity_uid', sa.String(), sa.ForeignKey('entity.uid', ondelete='CASCADE'),
                  primary_key=True, nullable=False),
        sa.Column('protocol', sa.String(), primary_key=True, nullable=False),
        sa.Column('target', sa.String(), primary_key=True, nullable=False, server_default=''),
        sa.Column('status', sa.String(), nullable=False, server_default='unknown'),
        sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
    )
    op.create_index('idx_entity_registration_protocol', 'entity_registration', ['protocol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entity_registration_protocol', table_name='entity_registration')
    op.drop_table('entity_registration')

    op.drop_index('ix_embedding_chunk_updated_at', table_name='embedding_chunk')
    op.drop_table('embedding_chunk')

    # Drop indexes/tables in reverse order
    op.drop_index('ix_entity_created_at', table_name='entity')
    op.drop_index('ix_entity_type_name', table_name='entity')

    # Best-effort: drop optional Postgres index
    op.execute("DROP INDEX IF EXISTS gin_entity_protocols;")

    op.drop_table('remote')
    op.drop_table('entity')
    # ### end Alembic commands ###
